#!/usr/bin/env false

import secret

MESSAGES = {
    'count_first': [  # {0} is sender_firstname
        'Hi {0}! Ich zähle hoch auf: 1. Zähl mal weiter, es gibt High Scores! ;)',
        'Oha, {0} fängt an zu zählen! Fangen wir an mit 1. Zähl mal weiter, es gibt High Scores! ;)',
        'Okay {0}, fangen wir an zu zählen. Los geht\'s mit 1. Zähl mal weiter, es gibt High Scores! ;)',
        'Eine 1 für {0}. So weit, so gut. Zähl mal weiter, es gibt High Scores! ;)',
    ],
    'count_subten_overtaken': [  # {0} is sender_firstname, {1} is user_dict['counts'], {2} is old_best_firstname
        'HA! Nimm *das*, {2}. {0} kann bis {1} zählen. Und du?',
        'Nimm dich in acht, {2}! Die {1} hat bisher nur {0} geschafft.',
        '{1}. Besser als das, was {2} so geschafft hat.',
    ],
    'count_subten_better': [  # {0} is sender_firstname, {1} is user_dict['counts']
        'Uiuiui! {0} hat jetzt sogar bis {1} gezählt.',
        '{1}! Das ist die höchste Zahl. Bisher. Noch nicht sehr hoch, aber immerhin.',
        'Schaut mal alle her! {0} kann bis {1} zählen!',
        'Immer einen Schritt weiter, was, {0}? Jetzt schon bei {1}.',
    ],
    'count_subten': [  # {0} is sender_firstname, {1} is user_dict['counts']
        'Jetzt bist du bei {1}, {0}.',
        'Als Nächstes kommt die {1}. Wusstest du das, {0}?',
        'Unglaublich aber wahr: Danach kommt die {1}.',
        '{0} ist jetzt bei {1}.',
    ],
    'count_high_overtaken': [  # {0} is sender_firstname, {1} is user_dict['counts'], {2} is old_best_firstname
        'HA! Nimm *das*, {2}. {0} kann bis {1} zählen. Und du?',
        '{1}: {0} kann also weiter zählen als {2}. Das merk ich mir.',
        '{0}, ich liebe dich. Noch nie zuvor hat jemand bis {1} gezählt. {2} hat es versucht, aber… reden wir nicht darüber.',
        '{1} ist eine ganz besondere Zahl. Findest du nicht auch, {0}? Besser als die Zahl von {2}.',
        'Auf dich kann man zählen, {0}! {1} ist ganz klar besser als die Zahl von {2}.',
        'HIGH SCORE! {0} kann bis {1} zählen. Und du, {2}?',
    ],
    'count_high_better': [  # {0} is sender_firstname, {1} is user_dict['counts']
        'HIGH SCORE! Jetzt bist du schon bei {1}.',
        '{1}?! Oh fuck yeah, {0} ;)',
        '{1}! Ein neuer Rekord von dir!',
        '{1}! Ohoho, du übertriffst dich mal wieder selbst, {0} ;)',
        'Mit {1} bist du sogar besser als wie du selbst, {0}!',
        '{0}. {1}. Muss man mehr sagen? :D',
        '{0}. {1}. Find ich gut!',
    ],
    'count_high_equal': [  # {0} is sender_firstname, {1} is user_dict['counts'], {2} is old_best_firstname
        'Gleichstand mit {2}, {0}! Ihr seid jetzt beide bei {1}.',
        '{1}, und es ist Kopf an Kopf zwischen dir und {2}. Wer von euch beiden kann weiter zählen?',
        'Es waren einmal {0} und {2}, und sie zählten friedlich bis {1}. Und wer macht den nächsten /count? ;)',
        'Fast geschafft, {0}! {1} reicht noch nicht ganz, um {2} zu überholen!',
        'Noch ein bisschen mehr, {0}! Mit {1} hast du {2} noch nicht ganz überholt!',
        'Sieh dich vor, {2}! {0} ist jetzt schon bei {1}!',
    ],
    'count_high': [  # {0} is sender_firstname, {1} is user_dict['counts'], {2} is old_best_firstname, {3} is highscore['number']
        '{1}. Gähn. Mach mal schneller, {2} ist schon bei {3}.',
        '{0}: {1}. Pah. {2} ist schon bei {3}.',
        'Eine {1} für {0}. Ganz okay, aber {2} hat schon {3}.',
        'Weiter geht\'s mit {1}.',
        'Danach kommt die {1}, {0}.',
        'Jaja, ganz nett. Aber die {3} von {2} finde ich besser.',
        'Das wären dann {1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        '{1}.',
        'Ohh, {1}. Ich mag die Zahl, {0}! ;)',
        '{1}?! Was ist das denn für eine Zahl. Zähl mal bis {3}, das ist viel geiler!',
        '{1}. Ganz okay, {0}.',
        'Mach schneller, {0}, du bist erst bei {1}!',
        'Du magst es gemächlich, {0}, oder? Deine {1} ist ganz okay.',
        'Aber natürlich, {0}. Hier ist deine {1}.',
        'Na meinetwegen, {0}. Jetzt kommt die {1}.',
        'Können wir nicht lieber über die {3} von {2} reden?',
        'Die Zahl ist so klein, {0}, die sprech ich nicht mal aus.',
        '{1}. Weißt du, es kommt halt *doch* auf die Grüße an, {0}.',
        'Auch {0} kann jetzt bis {1} zählen.',
        'Jetzt bist du schon bei {1}.',
    ],
    'roll': [  # {0} is sender_firstname
        'Eine 4.',
        'Du hast eine 4 gewürfelt, {0}.',
        'Es wurde eine 4.',
        '4 Augen, {0}.',
        'Es sind 4 Augen, {0}.',
        '{0}, es ist eine 4.',
        '{0}, du wirst es kaum glauben: Es ist eine 4!',
        'OMG, wie machst du das?! Es ist eine 4!',
    ],
    'plopp': [  # {0} is sender_firstname
        'Plopp',
        '(plop)',
        'PLOPP!',
        'Plopp.',
        'Plopp-plopp.',
        'PLOPPPLOPPPLOPP!',
        '(War schon geploppt, versuch es nochmal.)',
        '*raschelraschel*',
        'Plup',
        'plopp',
        'Plopp!',
        'Du scheinst dich ja richtig mit dem Poppen auszukennen, was? ;)',
        'Popp',
        'Pop',
        'Blub (Huch, der war wohl mit Wasser gefüllt.)',
    ],
    'unknown_command': [  # {0} is sender_firstname
        'Häh?',
        'Bittewas, {0}?',
        'Bestimmt weiß ich eines Tages, was das bedeuten soll, {0}.',
        'Ich habe nicht genügend Erfahrung, um diese Aufgabe auszuführen.',
    ],
}
